version: "3.8"

networks:
  my-poolpal:

volumes:
  rabbitmq_data:

services:

  ####################################
  # RabbitMQ: The messaging broker   
  ####################################
  rabbitmq:
    image: rabbitmq:3-management
    hostname: esd-rabbit
    restart: always
    networks:
      - my-poolpal
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes: 
      - rabbitmq_data:/var/lib/rabbitmq
 
  ###################################
  # Driver: The Driver microservice
  ###################################
  driver:
    build:
      context: ./
      dockerfile: driver.Dockerfile
    image: chirag02/driver:1.0
    restart: always

    networks:
      - my-poolpal
    depends_on:
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      dbURL: mysql+mysqlconnector://poolpal@host.docker.internal:3306/poolpal
      PYTHONUNBUFFERED: 1
    ports:
      - "5000:5000"
 
  #######################################################
  # Passenger : The Passenger Microservice
  #######################################################
  passenger:
    build:
      context: ./
      dockerfile: passenger.Dockerfile
    image: chirag02/passenger:1.0
    restart: always
    networks:
      - my-poolpal
    depends_on:
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      dbURL: mysql+mysqlconnector://poolpal@host.docker.internal:3306/poolpal
      PYTHONUNBUFFERED: 1
    ports:
      - "5001:5001"

  ###################################
  # Carpool: The Carpool microservice
  ###################################
  carpool:
    build:
      context: ./
      dockerfile: carpool.Dockerfile
    image: chirag02/carpool:1.0
    restart: always
    networks:
      - my-poolpal
    environment:
      dbURL: mysql+mysqlconnector://poolpal@host.docker.internal:3306/poolpal
      PYTHONUNBUFFERED: 1
    ports:
      - "5002:5002"

  ######################################
  # Carpeople: The Carpeople microservice
  ######################################
  carpeople:
    build:
      context: ./
      dockerfile: carpeople.Dockerfile
    image: chirag02/carpool:1.0
    restart: always
    networks:
      - my-poolpal
    environment:
      dbURL: mysql+mysqlconnector://poolpal@host.docker.internal:3306/poolpal
      PYTHONUNBUFFERED: 1
    ports:
      - "5010:5010"

  ###############################################
  # Add Passenger: The Add Passenger microservice
  ###############################################
  add_passenger:
    build:
      context: ./
      dockerfile: add_passenger.Dockerfile
    image: chirag02/add_passenger:1.0
    restart: always
    networks:
      - my-poolpal
    depends_on:
      - carpeople
      - carpool
    environment:
      carpeople_URL: http://carpeople/api/v1/carpeople/get_all_passengers
      carpool_URL: http://carpool/api/v1/carpool/get_all_carpools
      PYTHONUNBUFFERED: 1
    ports:
      - "5110:5110"

  #################################################
  # Match Carpools: The Match Carpools microservice
  #################################################
  match_carpools:
    build:
      context: ./
      dockerfile: match_carpools.Dockerfile
    image: chirag02/match_carpools:1.0
    restart: always
    networks:
      - my-poolpal
    depends_on:
      - carpool
      - carpeople
      - driver
    environment:
      carpeople_URL: http://carpool/api/v1/carpeople/get_all_passengers
      carpool_URL: http://carpool/api/v1/carpool/get_all_carpools
      driver_url: http://driver/api/v1/driver/get_driver_by_id/
      PYTHONUNBUFFERED: 1
    ports:
      - "5100:5100"

  ##################################
  # Review: The Review microservice
  ##################################
  review:
    build:
      context: ./
      dockerfile: review.Dockerfile
    image: chirag02/review:1.0
    restart: always
    networks:
      - my-poolpal
    environment:
      dbURL: mysql+mysqlconnector://poolpal@host.docker.internal:3306/PoolPal
      PYTHONUNBUFFERED: 1
    ports:
      - "5006:5006"

  ##################################
  # User: The User microservice
  ##################################
  user:
    build:
      context: ./
      dockerfile: user.Dockerfile
    image: chirag02/user:1.0
    restart: always
    networks:
      - my-poolpal
    environment:
      dbURL: mysql+mysqlconnector://poolpal@host.docker.internal:3306/PoolPal
      PYTHONUNBUFFERED: 1
    ports:
      - "5016:5016"
      
  #################################################
  # User Log: The User Log microservice
  #################################################
  user_log:
    build:
      context: ./
      dockerfile: amqp_user.Dockerfile
    image: chirag02/amqp_user:1.0
    restart: always
    networks:
      - my-poolpal
    depends_on:
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      dbURL: mysql+mysqlconnector://poolpal@host.docker.internal:3306/PoolPal
      PYTHONUNBUFFERED: 1

  #################################################
  # Dispute: The Dispute microservice
  #################################################
  dispute:
    build:
      context: ./
      dockerfile: dispute.Dockerfile
    image: chirag02/dispute:1.0
    restart: always
    networks:
      - my-poolpal
    environment:
      dbURL: mysql+mysqlconnector://poolpal@host.docker.internal:3306/PoolPal
      PYTHONUNBUFFERED: 1
    ports:
      - "5125:5125"
  

  #################################################
  # Payment Log : The Payment Logs microservice
  #################################################
  payment_logs:
    build:
      context: ./
      dockerfile: payment_log.Dockerfile
    image: chirag02/payment_logs:1.0
    restart: always
    networks:
      - my-poolpal
    environment:
      dbURL: mysql+mysqlconnector://poolpal@host.docker.internal:3306/PoolPal
      PYTHONUNBUFFERED: 1
    ports:
      - "5055:5055"
  
  #################################################
  # Payments: The Payments microservice
  #################################################
  payments:
    build:
      context: ./
      dockerfile: payments.Dockerfile
    image: chirag02/payments:1.0
    restart: always
    networks:
      - my-poolpal
    depends_on:
      - payment_logs
      - rabbitmq
    environment:
      paymentlog_URL: http://payment_logs/api/v1/paymentlogs/
      rabbit_host: rabbitmq
      rabbit_port: 5672
      PYTHONUNBUFFERED: 1
    ports:
      - "5004:5004"

  #################################################
  # Authentication: The Authentication microservice
  #################################################
  authentication:
    build:
      context: ./
      dockerfile: authentication.Dockerfile
    image: chirag02/authentication:1.0
    restart: always
    networks:
      - my-poolpal
    depends_on:
      - user
      - driver
      - passenger
    environment:
      user_URL: http://user/api/v1/user
      driver_URL: http://driver/api/v1/driver/get_driver_by_email/
      passenger_URL: http://passenger/api/v1/passenger/get_passenger_by_email/
      PYTHONUNBUFFERED: 1
    ports:
      - "5450:5450"
  
  #################################################
  # Process Refund: The Process Refund microservice
  #################################################
  process_refund:
    build:
      context: ./
      dockerfile: process_refund.Dockerfile
    image: chirag02/process_refund:1.0
    restart: always
    networks:
      - my-poolpal
    depends_on:
      - payment_logs
      - payments
    environment:
      dbURL: mysql+mysqlconnector://poolpal@host.docker.internal:3306/PoolPal
      paymentlog_URL: http://payment_logs/api/v1/paymentlog/get_intent_by_ID
      payments_URL: http://payments/api/v1/payments/refund
      PYTHONUNBUFFERED: 1
    ports:
      - "5120:5120"
  
  #################################################
  # Populate: The Populate microservice
  #################################################
  populate:
    build:
      context: ./
      dockerfile: populate.Dockerfile
    image: chirag02/populate:1.0
    restart: always
    networks:
      - my-poolpal
    depends_on:
      - carpeople
      - carpool
      - driver
      - passenger
    environment:
      carpeople_URL: http://carpeople:5010/api/v1/carpeople/
      carpool_URL: http://carpool:5002/api/v1/carpool/
      passenger_URL: http://passenger/api/v1/passenger/
      driver_URL: http://driver/api/v1/driver/
      PYTHONUNBUFFERED: 1
    ports:
      - "5700:5700"

  # #################################################
  # # Populate: The Populate microservice
  # #################################################
  # populate:
  #   build:
  #     context: ./
  #     dockerfile: populate.Dockerfile
  #   image: chirag02/populate:1.0
  #   restart: always
  #   depends_on:
  #     - carpeople
  #     - carpool
  #     - driver
  #     - passenger
  #   environment:
  #     carpeople_URL: http://carpeople:5010/api/v1/carpeople/
  #     carpool_URL: http://carpool:5002/api/v1/carpool/
  #     passenger_URL: http://127.0.0.1:5001/api/v1/passenger/
  #     driver_URL: http://127.0.0.1:5000/api/v1/driver/
  #     PYTHONUNBUFFERED: 1
  #   ports:
  #     - "5700:5700"

  #######################################################
  # Calculate Pricing: The Calculate Pricing microservice
  #######################################################
  calculate_pricing:
    build:
      context: ./
      dockerfile: calculate_pricing.Dockerfile
    image: chirag02/calculate_pricing:1.0
    networks:
      - my-poolpal
    restart: always
    environment:
      average_singapore_fuel_prices: 3.28
      average_mileage_singapore_cars: 16
      poolpal_commission: 5
      PYTHONUNBUFFERED: 1
    ports:
      - "5101:5101"

  #################################################################
  # Calculate Refund Amount: The Calculate Refund Amount microservice
  #################################################################
  calculate_refund_price:
    build:
      context: ./
      dockerfile: calculate_refund_amount.Dockerfile
    image: chirag02/calculate_refund_price:1.0
    networks:
      - my-poolpal
    restart: always
    depends_on:
      - carpool
    environment:
      carpool_URL: http://carpool/api/v1/carpool
      dbURL: mysql+mysqlconnector://poolpal@host.docker.internal:3306/PoolPal
      PYTHONUNBUFFERED: 1
    ports:
      - "5115:5115"
