FROM python:3-slim
WORKDIR /usr/src/app
COPY requirements.txt ./
RUN python -m pip install --no-cache-dir -r requirements.txt
COPY ./amqp_passenger.py .
COPY ./amqp_setup.py .
COPY ./passengerMS.py .
CMD [ "python", "./passengerMS.py" ]
