CREATE TABLE IF NOT EXISTS passengers (
    PID INTEGER AUTO_INCREMENT,
    PName VARCHAR(200) NOT NULL,
    PUserName VARCHAR(200) NOT NULL UNIQUE,
    PAge INTEGER NOT NULL,
    PGender CHAR(1) NOT NULL,
    PEmail VARCHAR(200)NOT NULL,
    PAddress VARCHAR(400) NOT NULL,
    PPhone INTEGER NOT NULL,
    PAccount_Created_At DATETIME DEFAULT NOW(),
    PRIMARY KEY(PID, PEmail)
);


CREATE TABLE IF NOT EXISTS carpooling (
    CPID INTEGER AUTO_INCREMENT,
    DID INTEGER NOT NULL,
    DriverFee FLOAT(2) DEFAULT 0,
    DateTime DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CPStartLocation VARCHAR(64) NOT NULL,
    CPStartCoordinates FLOAT(10) NOT NULL,
    CPendLocation VARCHAR(64) NOT NULL,
    CPEndCoordinates FLOAT(10) NOT NULL, 
    Status VARCHAR(64) NOT NULL,
    Capacity_remaining INTEGER NOT NULL,
    FOREIGN KEY (DID) REFERENCES driver(DID),
    PRIMARY KEY(CPID, DID)
);


CREATE TABLE `review` (
  `CPID` int NOT NULL,
  `DID` int NOT NULL,
  `PID` int NOT NULL,
  `PRating` int DEFAULT NULL,
  `DRating` int DEFAULT NULL,
  `PDescription` varchar(100) DEFAULT NULL,
  `DDescription` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`CPID`,`DID`,`PID`),
  CONSTRAINT `review_ibfk_1` FOREIGN KEY (`CPID`) REFERENCES `carpool` (`CPID`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `review_ibfk_2` FOREIGN KEY (`DID`) REFERENCES `driver` (`DID`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `review_ibfk_3` FOREIGN KEY (`PID`) REFERENCES `passenger` (`PID`) ON DELETE RESTRICT ON UPDATE RESTRICT
)

CREATE TABLE `staff` (
  `SID` int NOT NULL AUTO_INCREMENT,
  `SName` varchar(100) NOT NULL,
  `Gender` varchar(1) NOT NULL,
  PRIMARY KEY (`SID`)
)

