# Use the official Python image as the base image
FROM python:3.9-slim

# Set the working directory to /app in the Docker container
WORKDIR /app

# Copy the contents of your Flask application directory into the Docker container
COPY . /app

# Install the required Python packages using pip
RUN pip install -r requirements.txt

# Expose the port that the Flask application listens on
EXPOSE 5020 
EXPOSE 5045

# Start the Flask development server
CMD ["python", "run.py"]